# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\andre\OneDrive - Universidad Tecnológica de Pereira\Desktop\Proyecto final progra\2.2\UI\COMPLEMENTOS\SIMPLE\CALCULADORA.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(252, 347)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\andre\\OneDrive - Universidad Tecnológica de Pereira\\Desktop\\Proyecto final progra\\2.2\\UI\\COMPLEMENTOS\\SIMPLE\\../77b87efd1d87532d02949f34b1f67ef0.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.BOTON1 = QtWidgets.QPushButton(Form)
        self.BOTON1.setGeometry(QtCore.QRect(14, 48, 51, 41))
        self.BOTON1.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BOTON1.setObjectName("BOTON1")
        self.BOTON2 = QtWidgets.QPushButton(Form)
        self.BOTON2.setGeometry(QtCore.QRect(74, 48, 51, 41))
        self.BOTON2.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BOTON2.setObjectName("BOTON2")
        self.BOTON3 = QtWidgets.QPushButton(Form)
        self.BOTON3.setGeometry(QtCore.QRect(134, 48, 51, 41))
        self.BOTON3.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BOTON3.setObjectName("BOTON3")
        self.PARENTECIS_1 = QtWidgets.QPushButton(Form)
        self.PARENTECIS_1.setGeometry(QtCore.QRect(194, 48, 51, 41))
        self.PARENTECIS_1.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.PARENTECIS_1.setObjectName("PARENTECIS_1")
        self.BOTON4 = QtWidgets.QPushButton(Form)
        self.BOTON4.setGeometry(QtCore.QRect(14, 98, 51, 41))
        self.BOTON4.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BOTON4.setObjectName("BOTON4")
        self.PARENTECIS_2 = QtWidgets.QPushButton(Form)
        self.PARENTECIS_2.setGeometry(QtCore.QRect(194, 98, 51, 41))
        self.PARENTECIS_2.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.PARENTECIS_2.setObjectName("PARENTECIS_2")
        self.BOTON6 = QtWidgets.QPushButton(Form)
        self.BOTON6.setGeometry(QtCore.QRect(134, 98, 51, 41))
        self.BOTON6.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BOTON6.setObjectName("BOTON6")
        self.BOTON5 = QtWidgets.QPushButton(Form)
        self.BOTON5.setGeometry(QtCore.QRect(74, 98, 51, 41))
        self.BOTON5.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BOTON5.setObjectName("BOTON5")
        self.BOTON7 = QtWidgets.QPushButton(Form)
        self.BOTON7.setGeometry(QtCore.QRect(14, 148, 51, 41))
        self.BOTON7.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BOTON7.setObjectName("BOTON7")
        self.PUNTO = QtWidgets.QPushButton(Form)
        self.PUNTO.setGeometry(QtCore.QRect(194, 148, 51, 41))
        self.PUNTO.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.PUNTO.setObjectName("PUNTO")
        self.BOTON9 = QtWidgets.QPushButton(Form)
        self.BOTON9.setGeometry(QtCore.QRect(134, 148, 51, 41))
        self.BOTON9.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BOTON9.setObjectName("BOTON9")
        self.BOTON8 = QtWidgets.QPushButton(Form)
        self.BOTON8.setGeometry(QtCore.QRect(74, 148, 51, 41))
        self.BOTON8.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BOTON8.setObjectName("BOTON8")
        self.BOTON_C = QtWidgets.QPushButton(Form)
        self.BOTON_C.setGeometry(QtCore.QRect(134, 198, 51, 41))
        self.BOTON_C.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"background-color: rgb(255, 85, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BOTON_C.setObjectName("BOTON_C")
        self.BOTON0 = QtWidgets.QPushButton(Form)
        self.BOTON0.setGeometry(QtCore.QRect(74, 198, 51, 41))
        self.BOTON0.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BOTON0.setObjectName("BOTON0")
        self.MAS = QtWidgets.QPushButton(Form)
        self.MAS.setGeometry(QtCore.QRect(14, 198, 51, 41))
        self.MAS.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"background-color: rgb(0, 170, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.MAS.setObjectName("MAS")
        self.POR = QtWidgets.QPushButton(Form)
        self.POR.setGeometry(QtCore.QRect(14, 248, 51, 41))
        self.POR.setStyleSheet("\n"
"background-color: rgb(0, 170, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.POR.setObjectName("POR")
        self.SALIR = QtWidgets.QPushButton(Form)
        self.SALIR.setGeometry(QtCore.QRect(134, 298, 111, 41))
        self.SALIR.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.SALIR.setObjectName("SALIR")
        self.IGUAL = QtWidgets.QPushButton(Form)
        self.IGUAL.setGeometry(QtCore.QRect(194, 198, 51, 91))
        self.IGUAL.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.IGUAL.setObjectName("IGUAL")
        self.BOTON_AC = QtWidgets.QPushButton(Form)
        self.BOTON_AC.setGeometry(QtCore.QRect(134, 248, 51, 41))
        self.BOTON_AC.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"background-color: rgb(255, 102, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BOTON_AC.setObjectName("BOTON_AC")
        self.DIVIDIDO = QtWidgets.QPushButton(Form)
        self.DIVIDIDO.setGeometry(QtCore.QRect(74, 248, 51, 41))
        self.DIVIDIDO.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.DIVIDIDO.setObjectName("DIVIDIDO")
        self.PORCENTAJE = QtWidgets.QPushButton(Form)
        self.PORCENTAJE.setGeometry(QtCore.QRect(74, 298, 51, 41))
        self.PORCENTAJE.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.PORCENTAJE.setObjectName("PORCENTAJE")
        self.MENOS = QtWidgets.QPushButton(Form)
        self.MENOS.setGeometry(QtCore.QRect(14, 298, 51, 41))
        self.MENOS.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"background-color: rgb(0, 170, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.MENOS.setObjectName("MENOS")
        self.Valor = QtWidgets.QLabel(Form)
        self.Valor.setGeometry(QtCore.QRect(10, 10, 231, 31))
        self.Valor.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 81 14pt \"Rockwell Extra Bold\";")
        self.Valor.setText("")
        self.Valor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Valor.setObjectName("Valor")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 231, 31))
        self.label_2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 81 14pt \"Rockwell Extra Bold\";")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.BOTON1.raise_()
        self.BOTON2.raise_()
        self.BOTON3.raise_()
        self.PARENTECIS_1.raise_()
        self.BOTON4.raise_()
        self.PARENTECIS_2.raise_()
        self.BOTON6.raise_()
        self.BOTON5.raise_()
        self.BOTON7.raise_()
        self.PUNTO.raise_()
        self.BOTON9.raise_()
        self.BOTON8.raise_()
        self.BOTON_C.raise_()
        self.BOTON0.raise_()
        self.MAS.raise_()
        self.POR.raise_()
        self.SALIR.raise_()
        self.IGUAL.raise_()
        self.BOTON_AC.raise_()
        self.DIVIDIDO.raise_()
        self.PORCENTAJE.raise_()
        self.MENOS.raise_()
        self.Valor.raise_()

        self.retranslateUi(Form)
        self.SALIR.clicked.connect(Form.close) # type: ignore
        self.BOTON_C.clicked.connect(self.Valor.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CALCULADORA"))
        self.BOTON1.setText(_translate("Form", "1"))
        self.BOTON1.setShortcut(_translate("Form", "1"))
        self.BOTON2.setText(_translate("Form", "2"))
        self.BOTON2.setShortcut(_translate("Form", "2"))
        self.BOTON3.setText(_translate("Form", "3"))
        self.BOTON3.setShortcut(_translate("Form", "3"))
        self.PARENTECIS_1.setText(_translate("Form", "("))
        self.PARENTECIS_1.setShortcut(_translate("Form", "("))
        self.BOTON4.setText(_translate("Form", "4"))
        self.BOTON4.setShortcut(_translate("Form", "4"))
        self.PARENTECIS_2.setText(_translate("Form", ")"))
        self.PARENTECIS_2.setShortcut(_translate("Form", ")"))
        self.BOTON6.setText(_translate("Form", "6"))
        self.BOTON6.setShortcut(_translate("Form", "6"))
        self.BOTON5.setText(_translate("Form", "5"))
        self.BOTON5.setShortcut(_translate("Form", "5"))
        self.BOTON7.setText(_translate("Form", "7"))
        self.BOTON7.setShortcut(_translate("Form", "7"))
        self.PUNTO.setText(_translate("Form", "."))
        self.PUNTO.setShortcut(_translate("Form", "."))
        self.BOTON9.setText(_translate("Form", "9"))
        self.BOTON9.setShortcut(_translate("Form", "9"))
        self.BOTON8.setText(_translate("Form", "8"))
        self.BOTON8.setShortcut(_translate("Form", "8"))
        self.BOTON_C.setText(_translate("Form", "C"))
        self.BOTON0.setText(_translate("Form", "0"))
        self.BOTON0.setShortcut(_translate("Form", "0"))
        self.MAS.setText(_translate("Form", "+"))
        self.MAS.setShortcut(_translate("Form", "+"))
        self.POR.setText(_translate("Form", "X"))
        self.POR.setShortcut(_translate("Form", "*"))
        self.SALIR.setText(_translate("Form", "SALIR"))
        self.IGUAL.setText(_translate("Form", "="))
        self.IGUAL.setShortcut(_translate("Form", "Return"))
        self.BOTON_AC.setText(_translate("Form", "AC"))
        self.BOTON_AC.setShortcut(_translate("Form", "Backspace"))
        self.DIVIDIDO.setText(_translate("Form", "/"))
        self.DIVIDIDO.setShortcut(_translate("Form", "/"))
        self.PORCENTAJE.setText(_translate("Form", "%"))
        self.PORCENTAJE.setShortcut(_translate("Form", "%"))
        self.MENOS.setText(_translate("Form", "-"))
        self.MENOS.setShortcut(_translate("Form", "-"))
